### ISSUE TITLE
Content-Type：application/octet-stream 元数据无法处理

### ISSUE THREAD

**Issue by ctwon800** [EsunR/s3-image-handler#1]
请问一下，图片如果上传后Content-Type: application/octet-stream   或者是binary/octet-stream，这个就没办法进行图片的缩放了，这个需要怎么处理的？改成 image/jpg 这种的就可以正常进行图片处理，图片太多的情况下这个不太好弄呀

**Comment by EsunR** [comment]
https://github.com/EsunR/s3-image-handler/blob/4018028348eb70c85d8528e4acacd1f77c06458e/packages/origin-response/handler/cfHandler.ts#L57C4-L57C4

尝试修改一下或去掉这里的判断逻辑，这里对非图片资源进行了拦截

**Comment by ctwon800** [comment]
可以了，谢谢，注释这块代码就好了  666
